version: "3.8"

services:
  nginx-storage:
    build:
      context: .
    container_name: ezmanga_nginx_storage
    ports:
      # Map host port (from .env) to container port (from .env or Dockerfile default)
      - "${HOST_PORT}:${NGINX_PORT}"
    environment:
      # Pass environment variables to the container
      # These will override the defaults set in the Dockerfile and be used by envsubst
      NGINX_PORT: ${NGINX_PORT}
      SERVER_NAME: ${SERVER_NAME}
      ROOT_PATH: ${ROOT_PATH}
    volumes:
      - type: bind
        source: ${HOST_STORAGE_PATH:-./storage} # Use HOST_STORAGE_PATH from .env or default to ./storage
        target: ${ROOT_PATH}
      - type: bind
        source: ${HOST_STORAGE_PATH:-./minio-data}
        target: ${ROOT_PATH}/minio-data
    restart: unless-stopped
